### ISSUE TITLE
http://w3id.org/iot/qoi is not redirecting

### ISSUE THREAD

**Issue by tanktoo** [perma-id/w3id.org#1085]
Hi,
the URL http://w3id.org/iot/qoi is not redirecting to the URL written in the .htaccess file. Can someone check if I have any error in the htaccess?

Thanks and kind regards,
tanktoo

**Comment by davidlehn** [comment]
Yes, there issues in that .htaccess file.   The file is in the `iot/qoi` dir but has rules for `^qoi$`.  That is doubling up the `qoi` part.  You can see the redirects at https://w3id.org/iot/qoi/qoi.  Can just change those `^qoi$` parts to `^$`.  Or alternatively could move that .htaccess file up one dir.

**Comment by tanktoo** [comment]
Oh, thanks for the hint. Haven't seen this. Started a new pull request.
Thanks a lot!
