### ISSUE TITLE
chainpoint w3id context 404

### ISSUE THREAD

**Issue by dontcallmedom** [perma-id/w3id.org#1313]
https://w3id.org/chainpoint/v2 and https://w3id.org/chainpoint/v3 (used in the JSON schema and documented in https://github.com/perma-id/w3id.org/tree/master/chainpoint) resolve to 404
/cc @jasonbukowski

**Comment by jasonbukowski** [comment]
Thanks for bringing that to my attention. This has been corrected.

**Comment by dontcallmedom** [comment]
thanks!
