### ISSUE TITLE
FAIR_Tests is returning 404

### ISSUE THREAD

**Issue by markwilkinson** [perma-id/w3id.org#1674]
Hi Daniel, 

I'm a bit confused... since my last commit, I'm getting a 404 **from w3id** (not from my server).  It doesn't seem to redirect at all!

https://w3id.org/FAIR_Tests/tests/gen2_unique_identifier

Can you see anything wrong?

M

**Comment by dgarijo** [comment]
See comments from @davidlehn: https://github.com/perma-id/w3id.org/pull/1671
You are adding FAIR_Tests twice in the URL: https://w3id.org/FAIR_Tests/FAIR_Tests/tests/gen2_unique_identifier should work.

How to solve this?
Change:
`RewriteRule FAIR_Tests/(.*) https://fair-tests.137.120.31.101.nip.io/$1 [R=307,L]`
to
RewriteRule ^(.*) https://fair-tests.137.120.31.101.nip.io/$1 [R=307,L]
