### ISSUE TITLE
Unable to import/open ontology in Protege using w3id.org url

### ISSUE THREAD

**Issue by Sheeba-Samuel** [perma-id/w3id.org#2014]
I am using w3id.org to create persistent and de-referenceable namespaces for the ReproduceMe Ontologies.
I encounter error while direct importing ontology or opening ontology using URL in Protege using the w3id.org URL: 
https://w3id.org/reproduceme.

The error is as follows:
[Fatal Error] :31:28: Open quote is expected for attribute "href" associated with an  element type  "a".

Encountered " <FULLIRI> "<!DOCTYPE html> "" at line 1, column 1.

The repository with the .htacess file is available here: https://github.com/perma-id/w3id.org/tree/master/reproduceme
I am using Protege 5.5.0.

I tried with curl. The content negotiation is done properly. 
curl -sH "accept:application/rdf+xml" -L https://w3id.org/reproduceme

Any suggestion to fix this?

Thanks
Sheeba

**Comment by davidlehn** [comment]
You may need to debug what the Protege request is.  It probably has */* in it and the first .htaccess rule is hitting and resulting in the html file being returned.  And That html file has those href bugs in the inline javascript.

**Comment by dgarijo** [comment]
I think it's matching the first line (HTML) because you are returning:
RewriteCond %{HTTP_ACCEPT} \*/\* [OR]
which is basically anything in the form of */*
Please have a look at
https://github.com/perma-id/w3id.org/blob/master/okn/o/sd/.htaccess, which
is loading fine under Protege 5.5.0.
Best,
Daniel

**Comment by Sheeba-Samuel** [comment]
Thanks @davidlehn and @dgarijo for pointing out the error. The RewriteCond is removed from the .htaccess file and the import of the ontology works in Protege.
