### ISSUE TITLE
Review approval for admins

### ISSUE THREAD

**Issue by dgarijo** [perma-id/w3id.org#2145]
Hi,
after recent changes, I cannot approve my own pull requests, which is inconvenient. Would it be possible to bypass this somehow @davidlehn ?

**Comment by davidlehn** [comment]
@dgarijo Yeah, that's a bit too restrictive considering how we've been using it.  I disabled that rule for the master branch. 
 When we [convert to an org account](https://github.com/perma-id/w3id.org/issues/2121) we could make some people admins to get around the issue.  But that might be too much power for just handling this issue.  Will just have to trust people to ask and wait for approvals if needed.
