### ISSUE TITLE
Redirecting paths with urlencoded URIs fails (AllowEncodedSlashes server config?)

### ISSUE THREAD

**Issue by awagner-mainz** [perma-id/w3id.org#2853]
Hi all,

I have set up a server that offers a [reconciliation service](https://reconciliation-api.github.io/specs/latest/) for SKOS concept schemes. For this, it offers API endpoints that include the ConceptScheme's URI - url-encoded - in the request path. (For example, see <https://c111-064.cloud.gwdg.de/reconc/mpilhlt/https%3A%2F%2Fw3id.org%2Fmpilhlt%2Fworktime_role> or <https://c111-064.cloud.gwdg.de/reconc/mpilhlt/https%3A%2F%2Fw3id.org%2Fmpilhlt%2Fworktime_role/_preview/r2>.)

Now I would like to put this service behind a w3id.org redirection, too. My .htaccess thus has a [line](https://github.com/perma-id/w3id.org/blob/a6eca7f2af63da4b8c3efbf7936a7c8c4bf2f8e2/mpilhlt/.htaccess#L17) like this:

```htaccess
RewriteRule   ^reconcile/(.*)   https://c111-064.cloud.gwdg.de/reconc/mpilhlt/$1   [R=307,NE,L]
```

This seems not to work, however. Running curl fails as soon as the path includes an url-encoded forward slash:

```console
> curl -I https://w3id.org/mpilhlt/reconcile/https%3A
HTTP/1.1 307 Temporary Redirect
Date: Fri, 05 Aug 2022 22:31:37 GMT
Server: Apache/2.4.29 (Ubuntu)
Access-Control-Allow-Origin: *
Location: https://c111-064.cloud.gwdg.de/reconc/mpilhlt/https%3A
Content-Type: text/html; charset=iso-8859-1

> curl -I https://w3id.org/mpilhlt/reconcile/https%3A%2F
HTTP/1.1 404 Not Found
Date: Fri, 05 Aug 2022 22:31:49 GMT
Server: Apache/2.4.29 (Ubuntu)
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=iso-8859-1
```

I have tried with and without the `NE` (`NoEscape`) flag in the redirection rule, but this did not help. The required and the present behaviour correspond quite closely (including the "404" when encountering an encoded forward slash) to what is in the docs for the [AllowEncodedSlashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes) config option. So I assume setting this to `On` or - better, because more secure - `NoDecode` would help my case. However, this is not something that can be set in an htacccess file context. It needs to be set in the main or virtual site config. (I have tried to set it in my htaccess file, this led to "500" instead of "404" errors and I have since removed the line from my htaccess file again.)

Do you have a policy on enabling things such as this one? Would you be ready to enable it? (Or is it even already enabled and I have been doing other things wrong?)

Thanks in advance - also, thanks more generally for all your efforts in maintaining this fantastic service!!!

Andreas

PS. I think I will be pushing for the service to allow passing the vocab URI in a query parameter instead of path components anyway. In cursory testing, I had the following result, which seems to indicate it may in fact work. So it's not a showstopper. Still, I believe it would be nice to allow encoded path components.

```console
> curl -I https://w3id.org/mpilhlt/reconcile/endpoint?q=https%3A%2F
HTTP/1.1 307 Temporary Redirect
Date: Mon, 08 Aug 2022 12:35:56 GMT
Server: Apache/2.4.29 (Ubuntu)
Access-Control-Allow-Origin: *
Location: https://c111-064.cloud.gwdg.de/reconc/mpilhlt/endpoint?q=https%3A%2F
Content-Type: text/html; charset=iso-8859-1
```

**Comment by davidlehn** [comment]
I'm not sure what the implications are for options like `AllowEncodedSlashes`.  I'm inclined to not change defaults like that.

Encoded paths in paths gets tricky since you may end up needing double encoding or other wizardry to pass such URLs around.  Best to try and avoid all that if possible.

It might be better to ask on stackoverflow or similar for a solution with a basically bland default apache setup.

**Comment by awagner-mainz** [comment]
I can understand. I have no idea about the implications myself. With the docs saying there are security concerns that can be (partly?) alleviated with the `NoDecode` value, I guess it would be good to at least know what is being referred to before allowing something along these lines. And better be safe and leave everything as is than be sorry.

As I said, I will be going for doing what I want to do via a query parameter, so for me it's not even necessary any longer. I hope it is at least useful to have brought this to your attention and to have it on the record.

From my PoV, this issue can be closed.
