### ISSUE TITLE
W3C Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [429]

### ISSUE THREAD

**Issue by tuanphampmt** [perma-id/w3id.org#3667]
My name is Tuan, I am getting the following error:
```
Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [429].
JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
```

According to my understanding of this error, I seem to have sent many requests to two urls:
"https://www.w3.org/2018/credentials/v1",
"https://catenax-ng.github.io/product-core-schemas/SummaryVC.json", 

1. Can I ask if the w3.org organization seems to have limited my request? 
2. Can you help me solve this problem? I really need help to complete my work 
Sincerely thank

**Comment by davidlehn** [comment]
I see you also copied the issue over at https://github.com/w3c/vc-data-model/issues/1330.  I have doubts either project is relevant to this issue, but let's leave discussion in one place.  Closing this.
