### ISSUE TITLE
Broken link to openspring.net under Management on the w3id.org home page

### ISSUE THREAD

**Issue by rivettp** [perma-id/w3id.org#3705]
It gave a DNS error not just a 404.
I know a strength of the project is the resilience from multiple members, but it was off-putting to at least one person I referred to the site: not that this participant may no longer be in operation but that, apparently, the management consortium was not aware and the site updated accordingly.

**Comment by TallTed** [comment]
If I understand correctly, your (their) concern is that the link for [OpenSpring](http://openspring.net/) in the [w3id.org README.md](https://github.com/perma-id/w3id.org/blob/master/README.md) reports DNS resolution failure?

Thank you for the alert. I've pinged the domain registrant in question, and hopefully that will be resolved shortly.
