### ISSUE TITLE
dggs.org broken

### ISSUE THREAD

**Issue by st-keller** [perma-id/w3id.org#3721]
[w3id.org/dggs/ README](https://github.com/perma-id/w3id.org/tree/master/dggs) is mentioned as a good example for a README.md on the homepage (https://w3id.org).

But https://dggs.org/ is broken.

Referring to a living example would be a better choice.

**Comment by st-keller** [comment]
It was literally the first outgoing link I clicked on a project dedicated to perma-ids. So it didn't inspire confidence in this project. This was, what I wanted to point out. Thanks a lot for your clear and quick answer!
Nice README, yes indeed.

**Comment by nicholascar** [comment]
Oh dear, yes, a bit naughty letting the domain names go. I'll try and get this working again shortly. We are actually restarting work on DGGS via the OGC.

**Comment by nicholascar** [comment]
OK, ok, mostly fixed! Almost all the previously created `w3id.org/dggs` PIDs are now resolving again and the link in the README works!
