### ISSUE TITLE
How to redirect to Ontology documentation with Widoco

### ISSUE THREAD

**Issue by vChavezB** [perma-id/w3id.org#3793]
I am new to htaccess and wanted to ask if it is possible to write a rule that redirects to [Widoco ](https://github.com/dgarijo/Widoco) documentation.

For Widoco documentation, the vocabulary pattern is typically

`www.my_docs.com/index.html#www.MYONTOLOGY_IRI.COM#MyVocab`

An example:

My ontology documentation (generated with WIdoco) is located for example at `www.example/index-en.html`. 

I have a permanent Id at w3id.org such as `https://w3id.org/ex1`. Lets say I have a class called `MyClass` with URI `https://w3id.org/ex1#myClass`. Can I have an htaccess rule that redirects

`https://w3id.org/ex1#myClass` to `www.my_docs.com/index.html#https://w3id.org/ex1#myClass` ?

**Comment by dgarijo** [comment]
Hello,

I created the example repo for this purpose: https://github.com/perma-id/w3id.org/tree/master/example. Have look at that template for hints on how to the the content negotiation.

However, if things are correct, it should redirect
`https://w3id.org/ex1#myClass` to `www.my_docs.com/index.html#myClass`, not `www.my_docs.com/index.html#https://w3id.org/ex1#myClass`. That looks like the local ontology URI is not being recognized correctly.

**Comment by dgarijo** [comment]
Example: https://w3id.org/example#Researcher
