### ISSUE TITLE
Verifiable Credential JWS2020 incorrect content-type

### ISSUE THREAD

**Issue by vincentkelleher** [perma-id/w3id.org#3985]
Hi 👋 

I'm currently working on verifiable credentials using [`JsonWebSignature 2020`](https://www.w3.org/community/reports/credentials/CG-FINAL-lds-jws2020-20220721/)'s context (https://w3id.org/security/suites/jws-2020/v1) and I've noticed that the returned content-type isn't the valid `application/ld+json` value.

## Issue

When I use a tool such as [Zazuko's Shacl Playground](https://shacl-playground.zazuko.com/) to check my verifiable credentials  that use the `jws2020` context against Shacl shapes I get silent errors like the following :

```
Error: Unsupported JSON-LD media type application/json
```

I checked the response headers with a `curl` command and realised that the content-type was `application/json` instead of `application/ld+json`.

```bash
$ curl -I -L -Haccept:application/ld+json https://w3c.github.io/vc-jws-2020/contexts/v1/

HTTP/2 200
server: GitHub.com
content-type: application/json; charset=utf-8
permissions-policy: interest-cohort=()
last-modified: Thu, 29 Jun 2023 12:36:12 GMT
access-control-allow-origin: *
etag: "649d7abc-9a9"
expires: Mon, 25 Mar 2024 15:21:05 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: 4ACE:0E9F:434DDCB:4479A04:66019409
accept-ranges: bytes
date: Mon, 25 Mar 2024 15:11:05 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-par-lfpg1960064-PAR
x-cache: MISS
x-cache-hits: 0
x-timer: S1711379466.712227,VS0,VE102
vary: Accept-Encoding
x-fastly-request-id: bcfeab9b11ef9e3340658e11f5fc1057c4758c1a
content-length: 2473
```

### Fix the Context File

My first idea was to fix [the exposed context file](https://github.com/w3c/vc-jws-2020/blob/main/contexts/v1/index.json) by opening a merge request on the [`w3c/vc-jws-2020` repo](https://github.com/w3c/vc-jws-2020/) but I quickly found out it was archived.

![image](https://github.com/perma-id/w3id.org/assets/4272277/13d85a30-ddf1-4fea-956f-5911335d85ac)

### ~~Override the Content-Type~~

~~The next solution is to override the content-type through this repository by changing the [security .htaccess file](https://github.com/perma-id/w3id.org/blob/master/security/.htaccess#L75). I would have proposed a pull request with the fix but I'm not familiar with this project and I imagine that someone with knowledge could fix this is a jiffy.~~

EDIT : This is not possible as response headers cannot be overridden in the case of a redirect (please see https://github.com/perma-id/w3id.org/issues/3985#issuecomment-2019817587)

Could someone help me with this issue ? 😇

**Comment by dgarijo** [comment]
@vincentkelleher,
I would open a PR or ping the maintainers of the repo (
    Dave Longley (@dlongley)
    David I. Lehn (@davidlehn)
    Manu Sporny (@msporny)
    Orie Steele (@OR13)
) to tell them about the issue

**Comment by vincentkelleher** [comment]
I just tried out the solutions I imagined on a local test environment using an Apache2 `httpd` Docker container with `mod_rewrite` enabled and it's not possible to override the response headers to set the desired content-type so the only solutions I see are to :
- fix the archived repository if @OR13 can do something about it, that would help a lot of people in my case
- fork the `w3c/vc-jws-2020` repository and fix the issue there but other people will encounter it

**Comment by OR13** [comment]
I suggest forking, the W3C VCWG abandoned that suite.

You could also host the context file yourself, and not rely on the redirect.

**Comment by TallTed** [comment]
> 3. Host the context file you want with the proper media type and extension in a new location and update w3id.org to that location.

Note that this would mean that *any and all* who want to use https://w3id.org/security/suites/jws-2020/v1 would be hitting your new hosting location. You would be committing to maintaining and supporting that new location.

**Comment by vincentkelleher** [comment]
Hi @OR13, @msporny, @TallTed,

Thank you for your quick replies.

Indeed I understand that `JsonWebSignature2020` is a now deprecated solution so we should move away from it, I will discuss with our ecosystem to see which solution we can move towards such as `vc-jwt`. It was the main proofing solution that allowed us to use RSA encrypted keys as we use EV SSL certificates that are issued with that algorithm.

Anyway, we (at Gaia-X) aren't planning on becoming the sole maintainers of the JWS2020 context as it's not part of our main goal and seemingly JWS2020 won't be evolving anymore so a solution needs to be found 😊 

I'm closing this issue for the time being to avoid adding clutter to your issues. Hoping we'll find a good fit for our needs.
