### ISSUE TITLE
Documentation of the top-level Apache httpd configuration

### ISSUE THREAD

**Issue by larsw** [perma-id/w3id.org#4061]
Hi,

Is it possible to document how the Apache server (conf/httpd.conf) is set up?

**Comment by davidlehn** [comment]
It's possible.  We didn't put it up in the past for some reasons I'm forgetting.  It's a fairly minimal config and minimal mods enabled.  What did you want to know?  How to emulate it for testing?

**Comment by larsw** [comment]
The scenario was for local testing. I created a minimal httpd.conf that works, but if you do anything out of the ordinary, it would be nice to see our setup.
