### ISSUE TITLE
Conflicting name tao and TAO

### ISSUE THREAD

**Issue by marioscrock** [perma-id/w3id.org#4417]
When cloning the repo to local filesystems that are case-insensitive the two folders are merged and it is not possible to commit without introducing unwanted changes to one of the two folders.

![image](https://github.com/user-attachments/assets/75151095-9774-4fe2-bee9-2e9b9aafbae0)

**Comment by davidlehn** [comment]
Oops.  We try to avoid the issue but this one slipped through.  We'll likely have to rename/remove the newer one added here:
https://github.com/perma-id/w3id.org/pull/4380

**Comment by davidlehn** [comment]
Directory changed in https://github.com/perma-id/w3id.org/pull/4427.
