### ISSUE TITLE
Examples link broken in README for unknown reason

### ISSUE THREAD

**Issue by joshmoore** [perma-id/w3id.org#4580]
The link in:
```
Creating a new identifier:
   See w3id.org/examples for examples of .htaccess and README.md.
```
looks to be properly formatted but links to: https://w3id.org/](https://github.com/perma-id/w3id.org/tree/master/examples

**Comment by TallTed** [comment]
`https://w3id.org/examples` redirects to `https://github.com/perma-id/w3id.org/tree/master/examples`, and what I see in the [`README.md` source](https://raw.githubusercontent.com/perma-id/w3id.org/refs/heads/master/README.md) is `[w3id.org/examples](https://github.com/perma-id/w3id.org/tree/master/examples)`, just skipping the HTTP redirects (`301 Moved Permanently` -> `302 Found` -> `200`).

What's the problem as you see it?

**Comment by joshmoore** [comment]
Hmm.... re-rendering today I see the proper behavior as well. I can only imagine that it was Hackathon-Hotel behavior. Very sorry for the noise.
