### ISSUE TITLE
W3id.org seems to be down

### ISSUE THREAD

**Issue by IC-Standards** [perma-id/w3id.org#755]
Services like https://isitup.org/w3id.org and http://www.isitdownrightnow.com/w3id.org.html show it as down.

**Comment by davidlehn** [comment]
Server locked up and now won't restart.  We'll get it back online as soon as we can.

**Comment by davidlehn** [comment]
It's back online.  Apparently the vm/kernel was too old to handle a live migration the hosting service performed.  They restarted it.  Probably had a multi year uptime.
