### ISSUE TITLE
Conflicts between directories /un and /UN

### ISSUE THREAD

**Issue by mommi84** [perma-id/w3id.org#920]
On case-insensitive systems such as macOS, the two directories `/un` and `/UN` are considered the same and cause a conflict. The local branch cannot be synced, as it meets an endless loop.

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   UN/.htaccess

no changes added to commit (use "git add" and/or "git commit -a")
$ git stash
Saved working directory and index state WIP on master: 9f48a6e
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   un/.htaccess

no changes added to commit (use "git add" and/or "git commit -a")
$ git stash
Saved working directory and index state WIP on master: 9f48a6e
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   UN/.htaccess

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by davidlehn** [comment]
Hmm.  Strange no one had this problem yet.  MacOS is case preserving and I thought handled this sort of situation, but I guess not.  Or at least tools are not up to it.

@essepuntato @kohsah Would it be ok to replace the UN/ dir that redirects to un/ with a special top level htaccess rule that does the same?

**Comment by essepuntato** [comment]
Hi @davidlehn 

Yes, the solution proposed is fine.

Have a nice day :-)

S.

**Comment by davidlehn** [comment]
Moved UN redir to a top level .htacces.  Closing.  Reopen if there are still issues.

**Comment by mommi84** [comment]
Thanks! No idea why no one else had this problem yet – maybe because of different versions of `git`? Anyhow, macOS is case-preserving but not case-sensitive, so only one directory was getting cloned.
